=== Frawstcrabs/42v6-Framework/languages/langformat.dtd
<!ELEMENT language (description, helpsection*, documentation?, output, command*)>
<!ATTLIST language id CDATA #REQUIRED>
<!ATTLIST language author CDATA #IMPLIED>
<!ATTLIST language name CDATA #IMPLIED>
<!ATTLIST language site-link CDATA #REQUIRED>

<!ELEMENT extension (documentation?, command+)>
<!ATTLIST extension id CDATA #REQUIRED>
<!ATTLIST extension site-link CDATA #REQUIRED>

<!ELEMENT command (parenthelpsection?, description, helpsection*, documentation?, output, command*)>
<!ATTLIST command id CDATA #REQUIRED>
<!ATTLIST command name CDATA #REQUIRED>
<!ATTLIST command alias CDATA #IMPLIED>
<!ATTLIST command hidden (true) #IMPLIED>

<!ELEMENT description (#PCDATA)>
<!ELEMENT helpsection (#PCDATA)>
<!ATTLIST helpsection args CDATA #IMPLIED>
<!ELEMENT documentation (#PCDATA)>

<!ELEMENT parenthelpsection (#PCDATA)>
<!ATTLIST parenthelpsection args CDATA #IMPLIED>

<!ELEMENT output ((line|list|dict|choice|pluralgroup)*)>

<!ELEMENT line (#PCDATA)>
<!ATTLIST line id CDATA #IMPLIED>
<!ELEMENT list ((line|list|dict|choice|nonetype)+)>
<!ATTLIST list id CDATA #IMPLIED>
<!ELEMENT dict (entry+)>
<!ATTLIST dict id CDATA #IMPLIED>
<!ELEMENT entry ((line|list|dict|choice|nonetype)+)>
<!ATTLIST entry name CDATA #REQUIRED>

<!ELEMENT nonetype EMPTY>

<!ELEMENT choice (item+)>
<!ATTLIST choice id CDATA #IMPLIED>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item weight CDATA #IMPLIED>

<!ELEMENT pluralgroup (plural+)>
<!ATTLIST pluralgroup id CDATA #REQUIRED>
<!ELEMENT plural (#PCDATA)>
<!ATTLIST plural value CDATA #IMPLIED>
<!ATTLIST plural lower CDATA #IMPLIED>
<!ATTLIST plural upper CDATA #IMPLIED>

=== Frawstcrabs/42v6-Framework/languages/english/language.xml
<?xml version="1.0"?>
<!DOCTYPE language SYSTEM "langformat.dtd" [
  <!ENTITY call "&#xF000;">
  <!ENTITY defaultcall "&#xF001;">
  <!ENTITY zwsp "&#x200B;">
  <!ENTITY site "">
]>

<language author="N/A" id="english" name="English" site-link="">
  <description>
    A bot created using the 42v6 framework, which also hasn't updated its language files.
    You can find the github for this framework here: https://github.com/Frawstcrabs/42v6-Framework
    Feel free to check out the bot this framework was originally created for here: https://42.rockett.space/
  </description>
  <output>

    <!-- Error Messages -->
    <choice id="error_ratelimit">
      <item weight="0.8">You have reached the ratelimit for this command. Please try again later.</item>
      <item weight="0.15">There is a ratelimit on this command that you have reached. Please stop as the workload physically hurts me.</item>
      <item weight="0.05">Cool down please. I'm being worked to the bone and the spam doesn't help... You were ratelimited by the way, come back later.</item>
    </choice>
    <choice id="error_toggle">
      <item weight="0.95">This command has been disabled by the guild. For details, check `&call;toggle`</item>
      <item weight="0.05">Unless you're a mod, you're not using this command. Please direct any complaints to your administration and point them to `&call;toggle`</item>
    </choice>
    <line id="error_banned_user">You have been blacklisted from using my functions.</line>
    <line id="error_banned_server">Your server has been blacklisted. Sorry for the inconvenience.</line>
    <line id="error_bot_banned">I cannot run this command as you have been botbanned on this server.</line>
    <choice id="error_authority">
      <item>There is an authority check on this command: `{}`</item>
      <item>You are not authorised to use this command: `{}`</item>
      <item>I cannot complete this command. You require `{}`</item>
      <item>You need `{}` to continue.</item>
    </choice>

    <!-- Permissions -->
    <line id="permission_owner">This command is only usable by my developers.</line>
    <line id="permission_buds">This command is only usable by a select group of close friends.</line>
    <line id="permission_patrons">This command is only usable by Patreon supporters. &site;patreon.html</line>
    <line id="permission_pm">This command can only be used in private chat.</line>
    <line id="permission_no_pm">This command cannot be used in private chat.</line>
    <line id="permission_guild_owner">Only the server owner can use this command.</line>
    <line id="permission_guild_admin">You must have manage roles for the server to use this command.</line>
    <line id="permission_guild_manager">You must have manage channels for the server to use this command.</line>
    <line id="permission_channel_manager">You must have manage channels for this channel to use the command.</line>
    <line id="permission_bot_admin">You must be a server admin or have a role called "best friend" to use this command.</line>
    <line id="permission_guild_mod">You must have manage messages for the server to use this command.</line>
    <line id="permission_channel_mod">You must have manage messages for the channel to use this command.</line>
    <line id="permission_bot_mod">You must be a server mod or have a role called "friend" to use this command.</line>
    <line id="permission_shitposter">Both you and I need a role called "shitpost" or "shitpost machine" for you to use this command.</line>

    <!-- Pagination -->
    <line id="paginator_closed">Window Closed.</line>
    <line id="paginator_footer">Page {}/{}</line>
    <line id="paginator_paging_title">Pages:</line>

    <!-- Error Handling -->
    <line id="ARG_ERROR">
      It appears an error occurred while processing your command. Please consult `&call;help` for more information.
    </line>
    <line id="ARG_MISSING">
      It appears an argument was missing from your command. Please consult `&call;help` for more information.
    </line>
    <line id="INT_RESOLVE_error">
      An improper number was passed in your command. Please note this command only take whole numbers.
    </line>
    <line id="FLOAT_RESOLVE_error">
      An improper number was passed in your command.
    </line>
    <line id="MEMBER_RESOLVE_list_footer">
      Please enter only the number of the entry you want.
    </line>
    <line id="MEMBER_RESOLVE_list_too_long">
      The list of possible members was too long for me to post. Consider using a mention or discord tag instead.
    </line>
    <line id="MEMBER_RESOLVE_not_found">
      I couldn't find the member you wanted. Consider using a mention or discord tag instead.
    </line>

  </output>



</language>

=== Frawstcrabs/42v6-Framework/languages/english/moderation.xml
<?xml version="1.0"?>
<!DOCTYPE extension SYSTEM "langformat.dtd" [
  <!ENTITY call "&#xF000;">
  <!ENTITY defaultcall "&#xF001;">
  <!ENTITY zwsp "&#x200B;">
  <!ENTITY site "">
]>

<extension id="english" site-link="">
  <documentation>

  </documentation>

  <command id="remove" name="remove" alias="delete">
    <parenthelpsection>Deletes messages from the chat.</parenthelpsection>
    <description>
      Deletes messages from the chat.
      'limit' in all commands is the number of messages searched while deleting, not the number deleted.
    </description>
    <documentation>
      Deletes messages that match a certain criteria.

      In all subcommands, the `limit` parameter determines how much chat history will be searched when deciding on what to delete.
    </documentation>

    <output>
      <line id="invalid_subcommand">I do not know what you want me to remove. Use `&call;help command`</line>
      <line id="no_delete_permission">I require Manage Messages to delete messages.</line>
      <line id="no_logs_permission">I require Read Message History to use this command.</line>
      <line id="old_messages">I cannot delete messages older than 2 weeks.</line>
      <pluralgroup id="success">
        <plural value="1">I have deleted one message.</plural>
        <plural value="default">I have deleted {0} messages.</plural>
      </pluralgroup>
    </output>

    <command id="user" name="user" alias="users from">
      <parenthelpsection args="'@member' [['@member' ...] 'limit']">Deletes messages by a user.</parenthelpsection>
      <description>Deletes messages by a user or set of users.</description>
      <helpsection args="'@member' [['@member' ...] 'limit']">Deletes messages from one or many users.</helpsection>
      <documentation>
        Deletes messages from one or a group of users. Good for purging problematic conversations.
        `limit` must be specified as the last argument
        `@member` is the name, ID, Discord Tag, nickname or mention of the target user(s).
      </documentation>

      <output>
        <line id="no_target">I cannot find the user(s) you want to delete messages from.</line>
      </output>
    </command>

    <!-- Insert more subcommands here -->
  </command>
</extension>
